name: Post Today’s TruckersMP Event

on:
  schedule:
    - cron: '30 18 * * *'  # Runs daily at 12:00 AM IST (18:30 UTC)
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - pro

jobs:
  post-event:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set ENV based on trigger
        id: set-env
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            echo "ROLE_ID=${{ secrets.ROLE_ID1 }}" >> $GITHUB_ENV
            echo "ROLE_ID1=${{ secrets.ROLE_ID3 }}" >> $GITHUB_ENV
            echo "DISCORD_WEBHOOK=${{ secrets.DISCORD_WEBHOOK1 }}" >> $GITHUB_ENV
            echo "SHEET_ID=${{ secrets.SHEET_ID1 }}" >> $GITHUB_ENV
          else
            ENV_INPUT="${{ github.event.inputs.environment }}"
            if [[ "$ENV_INPUT" == "pro" ]]; then
              echo "ROLE_ID=${{ secrets.ROLE_ID1 }}" >> $GITHUB_ENV
              echo "ROLE_ID1=${{ secrets.ROLE_ID3 }}" >> $GITHUB_ENV
              echo "DISCORD_WEBHOOK=${{ secrets.DISCORD_WEBHOOK1 }}" >> $GITHUB_ENV
              echo "SHEET_ID=${{ secrets.SHEET_ID1 }}" >> $GITHUB_ENV
            else
              echo "ROLE_ID=${{ secrets.ROLE_ID2 }}" >> $GITHUB_ENV
              echo "ROLE_ID1=${{ secrets.ROLE_ID2 }}" >> $GITHUB_ENV
              echo "DISCORD_WEBHOOK=${{ secrets.DISCORD_WEBHOOK2 }}" >> $GITHUB_ENV
              echo "SHEET_ID=${{ secrets.SHEET_ID2 }}" >> $GITHUB_ENV
            fi
          fi



      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python post_event.py
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
